(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (call-the-cops)
    (error "Call the police"))
  (define incorrect-password-count 0)
  (define (dispatch p m)
    (if (eq? p password)
        (begin (set! incorrect-password-count 0)
               (cond ((eq? m 'withdraw) withdraw)
                     ((eq? m 'deposit) deposit)
                     (else (error "Unknown request: MAKE-ACCOUNT"
                                  m))))
        (begin (set! incorrect-password-count (+ incorrect-password-count 1))
               (if (>= incorrect-password-count 7)
                   (call-the-cops))
               (error "Incorecct password"))))
  dispatch)

(define acc (make-account 100 'secret-password))
((acc 'some-other-password 'deposit) 50)
